[build]
  base = "."
  publish = "public"
  command = "hugo"
  functions = ".netlify/functions"

[build.environment]
  GO_IMPORT_PATH = "github.com/micromdm/website"
  HUGO_VERSION = "0.128.2"

[context.production]
  command = "make netlify"
